### ISSUE TITLE
String compare handling

### ISSUE THREAD

**Issue by melrobin** [nickdrones/COSC-3342-Socket-Project#1]
In subsequent versions more robust string handling will have to be added.  Currently deal* will work.  This is just a placeholder issue.

**Comment by nickdrones** [comment]
I did fix it so it acknowledges "deal" and does successfully send a reply. at the moment, it sends 51 instances of "Card #:#" with the first # being 0-51 and the second # intended to be the value of the card, it's not sending the card value though, I'm still figuring that one out

**Comment by melrobin** [comment]
OK, I would recommend that you do a push to that you can ensure that you make incremental progress and do not accidentally create any regressions as you add code.  If you want you could also have a main version and create branches and merge as you create new features.
